epinio/epinio-end-to-end-tests

cypress/integration/applications.spec.ts, cypress/integration/namespaces.spec.ts, cypress/support/epinio.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/toplevelmenu.ts
- Add functions declaration in index.ts
- Functions with more than one argument now use named variables to help the argument passing as well as to improve code reading
- Add a Namespace regression test: application creation should not be possible if there is no namespace
- `cache_session` can be configured via env variable
- Remove unneeded `return`(s)
=> App without namespace

cypress/integration/01_first_connexion.spec.ts, cypress/support/epinio.ts
First time you log in Rancher, there are additional screens to handle:
- Confirm password specified in helm
- Confirm server URL and accept terms and conditions
This PR adds a test file to manage that case.
=> Handle first login in Rancher

cypress/integration/installation.spec.ts, cypress/plugins/index.ts, cypress/support/functions.ts, cypress/support/index.ts
Fix #5 
Install Epinio via Helm on Rancher with the default options
More scenarios will come later.
=> test: Install Epinio via helm on Rancher

cypress/integration/applications.spec.ts, cypress/integration/installation.spec.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/toplevelmenu.ts
- Deploy an app with replacing the default route.
- Deploy an app with env variables.
- Deploy an app with a mix of all units tests.
=> Add more Applications tests

cypress/integration/applications.spec.ts, cypress/integration/namespaces.spec.ts, cypress/support/epinio.ts, cypress/support/index.ts, cypress/support/tests.ts
This is helpful for multiple Helm scenarii tests, to avoid duplicate too much code.
=> Move tests to functions

cypress.json, cypress/integration/uninstall.spec.ts, cypress/support/functions.ts, cypress/support/index.ts
Fix #45 
Uninstall Epinio and remove the associated Helm chart.
=> Uninstall Epinio and remove helm chart

cypress/support/functions.ts
Add consistency to label by removing useless uppercase.
Changes needed due to https://github.com/epinio/helm-charts/pull/59
=> Remove useless s3 labels uppercase

cypress/integration/scenarios/install_with_default_options.spec.ts, cypress/integration/scenarios/install_with_s3_and_external_registry.spec.ts, cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
Add tests to validate 'Container Image' and 'Git URL' as sources for Epinio.
This should fix #31 and #32.
Validation:
=> Add new Applications tests

cypress/support/functions.ts
This PR fixes several small issues.
=> Fix minor issues

.github/workflows/ui-tests.yml, Makefile, cypress.json, scripts/install_rancher.sh
This PR adds a first Cypress execution in CI.
It's not perfect yet but it's needed to test the workflow.
Improvement and more cases will come in a following PR.
=> Add Cypress tests in CI

.github/workflows/ui-tests.yml
```
drwxr-xr-x 2 sles users 178 Jan 31 14:25 fixtures
drwxr-xr-x 4 sles users  41 Jan 31 14:25 integration
drwxr-xr-x 2 sles users  22 Jan 31 14:25 plugins
drwxr-xr-x 2 sles users  98 Jan 31 14:25 support
drwxr-xr-x 3 root root   23 Jan 31 14:56 videos
```
Videos folder are created with root permissions, so next workflow fails to delete it.
=> Change owner of Cypress generated files

.github/workflows/cypress_scenario1_chrome.yml, .github/workflows/reusable_ui_workflow.yml
I want to test if we can use reusable workflow for avoiding code duplication.
=> Experimentation - Use reusable workflow

.github/workflows/master_ui_workflow.yml, .github/workflows/scenario_2_cypress_firefox.yml
=> Add scenario 2 to CI (s3/ext_reg)

.github/workflows/master_ui_workflow.yml, .github/workflows/scenario_2_cypress_firefox.yml
Reverts epinio/epinio-end-to-end-tests#67
=> Revert "Add user option for firefox browser"

cypress/support/epinio.ts, cypress/support/functions.ts, cypress/support/index.ts
Locally tested successfully:
```
│ Tests:        14
│ Passing:      14
│ Failing:      0 
│ Pending:      0
│ Skipped:      0
│ Screenshots:  0
│ Video:        true
│ Duration:     18 minutes, 29 seconds
│ Spec Ran:     scenarios/install_with_default_options.spec.ts
```
```
│ Tests:        7
│ Passing:      7
│ Failing:      0
│ Pending:      0
│ Skipped:      0
│ Screenshots:  0
│ Video:        true
│ Duration:     4 minutes, 33 seconds
│ Spec Ran:     scenarios/install_with_s3_and_external_registry.spec.ts
```
=> Don't log sensitive informations like credentials

.github/workflows/master_ui_workflow.yml, cypress.json
Give a try to the Cypress Dashboard: https://docs.cypress.io/guides/dashboard/introduction
Free licence should be enough.
=> Configure / try Cypress dashboard

.github/workflows/master_ui_workflow.yml, cypress.json
Fix #62 
Enable artifacts upload and remove connection with Cypress dashboard, I didn't manage to make it work.
=> Enable artifacts upload

.github/workflows/master_ui_workflow.yml, Makefile, cypress/support/functions.ts
- fix: try to improve K3s waiting after installation
- fix: use a clean action to avoid chmod
- fix: add a workaround while creating an app
=> Add some fixes

cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
=> Test service unbinding

Makefile, scripts/install_cert-manager.sh, scripts/install_epinio.sh
Fix #92 
Tested successfully here:
Chrome: https://github.com/epinio/epinio-end-to-end-tests/runs/5332222495?check_suite_focus=true (test has failed for an other reason, will open a bug later)
Firefox: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/1898117259
=> Install Epinio the right way

.github/workflows/master_ui_workflow.yml, cypress/support/tests.ts
Fix #98 
Tests ok on Firefox: https://github.com/epinio/epinio-end-to-end-tests/runs/5403380287?check_suite_focus=true
and on Chrome as well: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/1932608110
=> Bump epinio ui version to 0.5.0

scripts/install_epinio.sh
Disable container registry and fix some helm values to use external registry
CI green here: https://github.com/epinio/epinio-end-to-end-tests/runs/5448247930?check_suite_focus=true
=> Fix external registry helm values

cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
=> Add application restart test

cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
=> Add application rebuild test

cypress/integration/scenarios/with_default_options.spec.ts
I forgot to configure rebuild and restart tests in scenario. I did it in unit tests only.
=> Add rebuild and restart tests to scenario

.github/workflows/master_ui_workflow.yml, cypress.json, cypress/fixtures/read_from_file.configuration, cypress/fixtures/read_from_file.service, cypress/integration/scenarios/install_with_default_options.spec.ts, cypress/integration/scenarios/with_default_options.spec.ts, cypress/integration/unit_tests/configurations.spec.ts, cypress/support/epinio.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
Because of https://github.com/epinio/epinio/pull/1287, we need to rename "Service" to "Configuration" in our e2e test suites.
=> Rename "Service" to "Configuration"

README.md
Badges only target scheduled event, it's better to target event on main branch.
=> Update README badge to target main branch

.github/workflows/master_ui_workflow.yml, cypress/support/tests.ts
Fix #111 
First step:
- try to reproduce it manually
- check how to debug cypress test and do it https://docs.cypress.io/api/events/catalog-of-events#Uncaught-Exceptions
=> e2e tests - Fix firefox test flakiness

.github/workflows/master_ui_workflow.yml
Bump k3s version we use in our e2e tests.
=> Bump k3s version to v1.22.7+k3s1

cypress/support/functions.ts
=> Adapt code to Rancher 2.6.6

.github/workflows/master_std_ui_workflow.yml
We don't need to patch the epinio-ui deployment anymore.
=> Remove epinio-ui deployment patch

Makefile, README.md
=> Update README with Cypress instructions

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui_workflow.yml
After debugging it, that's not so easy to use docker login action with reusable workflows.
Moreover, it doesn´t work because epinio installation is done in a cypress container...
=> Remove docker login action

.github/workflows/install_latest_standalone_ui.yml, Makefile, scripts/deploy_latest_dev_std_ui.sh
No impact, it adds new files to test running Cypress on latest dev standalone UI.
=> Install latest dev standalone ui

scripts/install_epinio.sh
`epinio settings update` command does not exist anymore, it has to be replaced by `epinio login` etc...
=> Fix epinio login command

.github/workflows/install_latest_standalone_ui.yml, Makefile, scripts/deploy_latest_dev_std_ui.sh, scripts/install_epinio.sh, scripts/start_cypress_tests.sh
Fix #178 
The new workflow passed [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2508180610) :heavy_check_mark:
=> Improve test with latest dev standalone UI

.github/workflows/applications_std_ui.yml, .github/workflows/configurations_std_ui.yml, .github/workflows/menu_std_ui.yml, .github/workflows/namespaces_std.ui.yml
This PR is a proof of concept to check if we can easily split our big scenario in smaller ones.
First part of https://github.com/epinio/epinio-end-to-end-tests/issues/185
=> Create smaller Cypress workflows

.goreleaser-dashboard-qa.yml, scripts/patch_epinio-ui.sh
CI OK:
https://github.com/epinio/epinio-end-to-end-tests/runs/7026108302?check_suite_focus=true
=> Switch to an official docker hub account

cypress/support/functions.ts
CI fixed: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2574181037
=> Remove hardcoded PHP version

cypress/support/functions.ts
Related issue #209 
Added Reg Exp verification on URL from created apps with random routing added after [this](https://github.com/epinio/epinio/pull/1640) issue
=> Adding Regexp to check added Routes on new apps

.github/workflows/master_std_ui.yml, scripts/install_epinio.sh
* Temporary adding SESSION_KEY env variable into workflow yam
* handling EXTRAENV vars by epinio_install.sh script
=> Basic extraEnv handling for installing epinio chart

cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts
Related issue: https://github.com/epinio/epinio-end-to-end-tests/issues/218
- Removing has suffix checkup after https://github.com/epinio/epinio/pull/1710
- Skipping Github Source test until release.
=> Removing has suffix checkup

.github/workflows/master_rancher_ui_workflow.yml, cypress/plugins/index.ts, cypress/support/functions.ts
Signed-off-by: Tomas Hehejik <thehejik@suse.com>
=> Basic extraEnv handling for installing epinio chart from rancher-ui

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui.yml
Intentionally keeping the commented vars in place for future usage if needed.
=> Unset EXTRAENV variables in workflows

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui.yml
=> Replace ::set-output by GITHUB_OUTPUT

cypress/support/epinio.ts, cypress/support/functions.ts
- firstLogin checkbox text changed
- Getting Started box is not present anymore
- Description of the upstream epinio chart changed
Tested here:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3280701680
=> Fixes for rancher-ui tests

scripts/patch_epinio-ui.sh
Tested [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3469197908/jobs/5795899011#step:13:9)
=> Use epinio-ui:latest-next image for tests

scripts/install_epinio.sh
ref. https://github.com/epinio/epinio/issues/1918
Test run triggered:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3601581558
=> Add s3.region when using external AWS S3 bucket

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui.yml, .github/workflows/master_std_ui_experimental.yml, scripts/create_docker_secret.sh
ref. #302
testrun https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4354419659/jobs/7609690539#step:12:96
=> Add ghcr.io secrets for pulling images

scripts/install_rancher_experimental.sh
Removing leftover on `install_rancher_experimental.sh` script
=> [Cypress] fixing leftover on rancher experimental 

scripts/install_rancher_experimental.sh
Fixing wrong value in echo to display Kubernetes version
=> [Cypress] Fixing wrong echo in k8s version

scripts/install_rancher.sh
Attempt to lower performance demand for rancher tests.
=> Only one rancher replica

cypress/support/functions.ts
Updating Dex login label after https://github.com/epinio/ui/issues/240
Local
=> Updating dex login label

.github/workflows/update-tests-description.yaml, Makefile, scripts/generate-readme, scripts/generate-tests-description
This is to have an automated list of QA/integration tests.
=> ci: add automation to generate README.md for tests

scripts/values-users.yaml
Adapt `values-user.yaml` to be compatible with the new schema introduced by `https://github.com/epinio/epinio/pull/2656`.
Testruns:
FF https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6874909692
Cr https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6875376863
=> Adapt users to new roles

cypress/e2e/unit_tests/menu.spec.ts, cypress/support/functions.ts
Implements https://github.com/epinio/epinio-end-to-end-tests/issues/396
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/7018264102/job/19093281092#step:14:80
=> Adding UI non-admin Dex test

.github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml
Ensure runners in Rancher tests stay on the same runner
=> Correctly allocate wd accross runner
