epinio/epinio-end-to-end-tests

cypress.json, cypress/integration/s3_and_external_registry.spec.ts, cypress/plugins/index.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/toplevelmenu.ts
Fix #46 
This PR adds a new test where s3 and external registry are configured in the installation screen.
It also adds robustness by fixing two part of codes where tests fail sporadically.
=> S3_external_reg

cypress.json, cypress/integration/applications.spec.ts, cypress/integration/namespaces.spec.ts, cypress/integration/s3_and_external_registry.spec.ts, cypress/integration/services.spec.ts, cypress/support/epinio.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
Add tests for the `Services` menu.
This should fix #34, #35, #36, #38, #39 and #40.
Without the `services` functions:
With the `services` functions:
**NOTE:** the `it` messages have been modified in the latest version, to be more verbose.
=> Add services tests

.github/workflows/master_ui_workflow.yml, .github/workflows/scenario_2_cypress_firefox.yml
Current Firefox test fails with:
```
Can't run because you've entered an invalid browser name.
Browser: 'firefox' was not found on your system or is not supported by Cypress.
Cypress supports the following browsers:
- chrome
- chromium
- edge
- electron
- firefox
You can also use a custom browser: https://on.cypress.io/customize-browsers
Available browsers found on your system are:
- chrome
- electron
```
https://github.com/cypress-io/github-action#firefox
We must specify --user 1001 for starting Firefox
=> Add user option for firefox browser

README.md
Fix #72 
Explain that our Cypress tests are now executed every night and add badges to know CI state.
I've also removed part that will be quickly out-of-date.
=> Add CI process in the README

.github/workflows/master_ui_workflow.yml, .github/workflows/scenario_2_cypress_firefox.yml, README.md
Code added by https://github.com/epinio/epinio-end-to-end-tests/pull/70 didn't work because we should have deleted cache in our self-hosted runner.
After doing more tests in my lab, it seems it works now.
=> Add Firefox test back

.github/workflows/master_ui_workflow.yml, Makefile
Tested on my local GH runner: https://github.com/ldevulder/epinio-end-to-end-tests/actions/runs/1843749909
Step 2 fails because I don't have a proper Docker configuration, but this PR is about K3s installation/uninstallation and these steps are OK.
=> Use k3s v1.21 + permissions fixes

cypress/support/tests.ts
Sample service has to be deleted at the end of the newAppWithService test. 
Otherwise, test fails with message 'Service service01 already exists'
Failed test: https://github.com/epinio/epinio-end-to-end-tests/runs/5332222495?check_suite_focus=true
=> Delete sample service at the end of tests

.github/workflows/scenario_1_cypress_chrome.yml, .github/workflows/scenario_2_cypress_firefox.yml
Bumped to `cypress:borwsers:node16.14.0-slim-chrome99-ff97)`
=> Bump cypress container image to latest

cypress/integration/scenarios/with_default_options.spec.ts, cypress/integration/unit_tests/applications.spec.ts
The restart test is not stable enough, it breaks CI so It needs improvements.
I remove it temporary while I'm doing investigations.
=> Disable restart and rebuild tests

cypress/support/functions.ts, cypress/support/tests.ts
Fix #113 
This PR adds few things:
- Increasing delay when a key is typed (avoid using `cy.wait` after typing with the default delay)
- Do not check header in clickEpinioMenu because header can now contains help message so we need to be more precise for checking in which menu we are (`cy.get('.m-0')`). It also permits do remove wait calls.
- Removing `cy.wait` calls
=> Replace cy.wait calls

cypress/integration/scenarios/with_default_options.spec.ts, cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts
These tests were disabled because they introduced random issues in the CI.
It should be good now as I've disabled the check on the instance availability percentage. 
It's not ready in the UI yet but the check will be on the restart counter.
=> Enable applications restart and rebuild tests

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui_workflow.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_1_chrome_std_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml, .github/workflows/scenario_2_firefox_std_ui.yml, Makefile
First part for #95 
I have to duplicate GH workflows and switching their names to do not break the CI.
At the end, the purpose is to test both Rancher and Standalone UI and to do proper things, we need to install Epinio via Rancher in the Rancher test.
For testing these new workflows, I have to merge this PR, otherwise I can not trigger them on other branches...
=> Add Epinio installation back via Rancher - First part

cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
Fix #129 and fix #128 
This [code](https://github.com/epinio/epinio-end-to-end-tests/pull/130/files#diff-aa81749832032471ec95581351571f6effa7d9b9c2ae35ebdf7ffae4fb70cd38R37-R40) is voluntary commented because we are blocked by https://github.com/epinio/epinio-end-to-end-tests/issues/126
However, I successfully tested these functions in my local Cypress lab.
=> Test app log and app shell buttons

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui_workflow.yml, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts
Fix #126 
Fix #131 
This PR addresses few issues which need to be fixed together to be well tested:
=> Adapt code for new application source types

cypress/integration/scenarios/install_with_default_options.spec.ts, cypress/integration/scenarios/install_with_s3_and_external_registry.spec.ts, cypress/integration/unit_tests/installation.spec.ts
Before this PR, we installed Epinio (in the Rancher UI)  using the official helm repo, that means we could only test released helm chart. It does not make a lot of sense, we need to test before releasing.
Instead of using the Helm repo, we can use a git URL to target the main version of our Helm Chart, that's so much better and this PR brings that.
=> Use git repo to deploy Epinio

cypress/support/tests.ts
Change Git Url for one of our application used in e2e tests.
git-url-app-test => example-go
=> Rename app used by Git Url

cypress-with-epinio-cert.json, cypress.json
This PR addresses this Cypress comment:
```
The experimentalSessionSupport configuration option was removed in Cypress version 9.6.0 and replaced with 
experimentalSessionAndOrigin. Please update your config to use experimentalSessionAndOrigin instead.
```
=> [Cypress] - Replace deprecated experimentalSessionSupport option

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui_workflow.yml, Makefile, cypress/integration/scenarios/install_with_default_options.spec.ts, cypress/integration/scenarios/install_with_s3_and_external_registry.spec.ts, cypress/integration/scenarios/with_default_options.spec.ts, cypress/integration/scenarios/with_s3_and_external_registry.spec.ts, cypress/integration/unit_tests/applications.spec.ts, cypress/integration/unit_tests/configurations.spec.ts, cypress/integration/unit_tests/first_connexion.spec.ts, cypress/integration/unit_tests/menu.spec.ts, cypress/integration/unit_tests/namespaces.spec.ts, cypress/plugins/index.ts, cypress/support/functions.ts, cypress/support/tests.ts, scripts/install_rancher.sh
Fix #91 
This PR mainly brings the capability to execute our Cypress tests on the Epinio standalone UI.
Rancher UI Chrome: ✅  - https://github.com/epinio/epinio-end-to-end-tests/runs/6419108443?check_suite_focus=true
Rancher UI Firefox: ✅ - https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2318031640
Epinio UI Chrome: ✅ - https://github.com/epinio/epinio-end-to-end-tests/runs/6418567388?check_suite_focus=true
Epinio UI Firefox: ✅ - https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2317782432
=> Make the code working on the std UI

.github/workflows/master_std_ui_workflow.yml
helm-chart submodule in epinio/epinio repo points to this commit https://github.com/epinio/helm-charts/tree/80075ac4334cb77f82f043f4601dc52fbae1871f
So it does not get the latest epinio-ui version.
=> Patch epinio-ui version

cypress-with-epinio-cert.json, cypress.json
Scenarios which have been deleted must be removed from the config files, otherwise you will get this error:
`[Error: ENAMETOOLONG: name too long, stat 'cypress/integration/cypress/integration/cypress`
=> Remove outdated scenarios from cfg files

cypress/support/functions.ts
This PR increases the timeout of the app log tab.
It also add sthe app logs check back as https://github.com/epinio/ui/issues/100 fixed.
CI is green with the PR: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2408959557
=> Increase tab timeout and enable app logs check

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui_workflow.yml, .gitignore
Sometimes, we reach the rate limit of docker hub and tests fail:
```
Events:
Type     Reason     Age                From               Message
----     ------     ----               ----               -------
Normal   Scheduled  82s                default-scheduler  Successfully assigned epinio/kubed-58dd46c5c9-dsdm9 to gha1-runner-0
Normal   Pulling    35s (x3 over 81s)  kubelet            Pulling image "appscode/kubed:v0.13.2"
Warning  Failed     31s (x3 over 76s)  kubelet            Failed to pull image "appscode/kubed:v0.13.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/appscode/kubed:v0.13.2": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/appscode/kubed/manifests/sha256:40ca90967d4a43d03c590a1c4b233 …
```
=> Add docker login action due to rate limiting

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui_workflow.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_1_chrome_std_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml, .github/workflows/scenario_2_firefox_std_ui.yml, Makefile, cypress/support/functions.ts, scripts/create_docker_secret.sh, scripts/install_epinio.sh
Fix #167 
We have to push a secret to configure the docker credentials and avoid using an anonymous account.
CI:
Firefox / Rancher UI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/2415707285 :heavy_check_mark:
=> [Cypress] - Push docker secret in epinio

cypress/integration/unit_tests/applications.spec.ts
Linked to issue [#161 ](https://github.com/epinio/epinio-end-to-end-tests/issues/161)
The purpose is to clean applications from `applications.spec.ts` at the beginning of each test.
I assumed we will use all the time "testapp" as based.
If we want generic, it needs to be further implemented
=> adding cleansing prior each application test

cypress/integration/scenarios/with_default_options.spec.ts
Sibling of [#162].
It adds cleaning mechanism for sample applications (using testapp as name) and configurations (using configurations01 as name)  at the begining of the test for scenario: `with_default_options.spec.ts`
Tested locally and worked
=> Added cleaning to app tests in with_default tests

cypress/integration/scenarios/with_default_options.spec.ts, cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts
Basically, we do not have expected results with this PR #169, because the cy.exec call works only if Cypress is running in the same machine as k8s and that's not always the case.
This PR adds a quick workaround to fix it, we use the UI do delete the leftovers.
Maybe it could be improved by using an API call but I'm not sure it will be  faster because after all, the longest part is the deletion, so it will happen in both cases.
The second commit adds more precision to select the configuration tab, it's needed due to the introduction of the service feature.
Result with this [branch](https://github.com/epinio/epinio-end-to-end-tests/runs/6698982003?check_suite_focus=true):
Even if the first test fails and leave an app with testapp name, the others tests ran correctly.
=> Workaround to delete app and configuration before each

cypress/support/tests.ts
Sibling of #151 
Removing the `deleteConfiguration` method from `downloadManifestAndPushApp` within `runApplicationsTest` in `tests.ts`
The information within the manifest is not for configuration creation, but binding, so the configuration previously established, must  exist for the test to pass.
=> Remove deleteConfiguration prior manifest app upload

cypress/support/tests.ts
This PR disables the rebuild check due to this bug https://github.com/epinio/ui/issues/126
=> Disable rebuild check due to a bug

.github/workflows/master_std_ui.yml, .github/workflows/scenario_1_chrome_std_ui.yml, .github/workflows/scenario_2_firefox_std_ui.yml, scripts/start_cypress_tests.sh
Now that we have a [workflow](https://github.com/epinio/epinio-end-to-end-tests/pull/181) to deploy latest standalone UI.
We can modify other workflow files to call the new master file (master_std_ui.yml), yes we are using [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows) here.
Fix #179
=> Move Cypress tests on new STD UI CI

cypress/integration/scenarios/with_default_options.spec.ts, cypress/integration/scenarios/with_s3_and_external_registry.spec.ts, cypress/integration/unit_tests/menu.spec.ts, cypress/integration/unit_tests/namespaces.spec.ts, cypress/support/epinio.ts, cypress/support/functions.ts, cypress/support/index.ts, cypress/support/tests.ts, cypress/support/toplevelmenu.ts
Adapting cypress tests to new changes after 9.0-0.0.3 updates.
Related issue #174 
Updates done:
- Removed outdated tests: it('Try to push an application without any namespace')  
- Create namespace from get started button
- Check new options on left menu (advanced settings, services, etc)
- Added functionalty to delete all workspaces.
- Added checkup of new epinio page on applications when no namespaces exist
- Added check on Application Charts
- Locators adaptation
=> Adapting Cypress to 9.0-0.0.3

cypress/support/tests.ts
These two tests were disabled due to opened bugs.
As the bugs are fixed, we can enable them back.
=> Enable rebuild and app shell tests back

.github/workflows/build_latest_epinioUI.yml, .goreleaser-dashboard-qa.yml
In every CI tests, we build latest dashboard and it's time consuming and not efficient at all.
The good way is to build a docker image with latest epinio-ui and publish it in a sandbox repo.
Then, each CI tests can pull it and run faster.
This PR only adds two files, it won't break anything and I have to merge it to try the workflow...
If something is wrong, I will be able to fix it and test the CI from my branch.
=> Build and publish latest UI as draft binary

.github/workflows/master_std_ui.yml, .github/workflows/std_ui_latest_firefox.yml, scripts/install_epinio.sh
As we are now using inherit for sharing secret between template and child workflow, I had to rework how we detect we need to enable s3 when epinio is installed. I simply use a new env var: `S3`
Firefox test green: https://github.com/epinio/epinio-end-to-end-tests/runs/7036981269?check_suite_focus=true
And we can see that our app was pushed to external registry:
=> Rework how to enable s3

cypress/integration/unit_tests/applications.spec.ts, cypress/support/functions.ts, cypress/support/tests.ts
Test implementation of https://github.com/epinio/epinio-end-to-end-tests/issues/215
**Test covers:**
- Deploy example-go (https://github.com/epinio/example-go) using new feature SourceType=GitHub
- Ensure these fields are selected: username=epinio; repository=example-go; branch=main; commit=latest. It also uses an env var needed  for this application.
- Checks application name and env var.
**Results (locally run**):
Note: at the moment of this test it does not cover checking visually the application using `checkCreatedApp` method. The reason is the local run uses an URL (https://192.168.1.44:8005/)  which is different from the one present in Routes (https://testapp-nnnn.172.19.0.3.omg.howdoi.website) and would force some rework on the code just for testing purposes. This should be …
=> UI test for Github source type

.github/workflows/master_std_ui.yml
Related issue: https://github.com/epinio/epinio-end-to-end-tests/issues/223, https://github.com/epinio/epinio-end-to-end-tests/issues/218
Disabling temporarily patching of latest qa image epinio-ui-qa:latest since it seemed not working over a month. 
It seemed that latest changes on v.1.2.0 were not reflected on version from next day after release:
https://github.com/epinio/epinio-end-to-end-tests/runs/8263707860?check_suite_focus=true
After disabling it we capture the latest 1.2.0 version. Here it is a link to CI done while testing the full flow:
https://github.com/epinio/epinio-end-to-end-tests/runs/8270729048?check_suite_focus=true
=> Disabling qa latest image pull until fixed

.github/workflows/build_latest_epinioUI.yml
Fixes #223
Bump of node is needed, I used the same value as used in official release job https://github.com/rancher/dashboard/commit/fca2e4d07e281de778be12bb0c16f279f6362916
The image was updated on dockerhub already after running the job in my PR branch, see https://hub.docker.com/r/epinioteam/epinio-ui-qa/tags
=> Bump node version for epinioUI build

cypress/support/index.ts
Fix for Firefox tests here: https://github.com/epinio/epinio-end-to-end-tests/issues/229
- Adding handling of broken promises to avoid test being broken
Local:
CI: 
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3052417104/jobs/4921782995
=> adding handling erros for uncaught promises

cypress/integration/unit_tests/menu.spec.ts, scripts/values-users.yaml
Added UI automation for this issue: https://github.com/epinio/epinio/issues/1679
Related test for passwords: https://github.com/epinio/epinio-end-to-end-tests/pull/208
- Added UI test with special character username (user@test) . Password also contains special character to ensure it works.
Local test pass:
CI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3059323997/jobs/4936566901
=> [Cypress] Adding test for login usernames with special characters

cypress/integration/unit_tests/menu.spec.ts
Automated test for: https://github.com/epinio/epinio-end-to-end-tests/issues/214
- Bottom link with version number takes user to `about page` with binaries
- Version number from About page matches the one in main
- Back button works
- All links work
- Binaries are downloaded and names are checked in the download folder
- `See all packages` link takes the user to the right version, checks element in page and takes screenshot
- Version number is checked for all links
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3088337610/jobs/4994689441
=> [Cypress] Adding UI test to check binaries link and version

cypress/support/functions.ts
This fixes an issue when `epinioInstall` function was unable to create new `epinio` namespace when installating `epinio` from recent Rancher v2.6.8 by using upstream epinio helm chart. Before that it was installed into `default` namespace instead.
~I'm sure the proposed solution is sub-optimal but it works. Ideally we should select the `Create a New Namespace` entry from namespace dropdown by pre-loading the dd entires and selecting (and validating) the proper one but so far I have no idea how to achieve that.~
Edit 092722: used the solution provided by @juadk, thanks
=> Fix epinio namespace creation in rancher

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml, README.md, cypress/integration/unit_tests/installation.spec.ts, cypress/integration/unit_tests/menu.spec.ts, cypress/support/index.ts
Rancher UI tests now using epinio ingress url address link instead of Epinio icon which is not available anymore.
* I had to split cypress UI `master_rancher_ui_workflow.yml` into three steps, each with its own env vars to be able login to corresponding service (rancher and epinio): 
- epinio installation in rancher UI
- ~epino testing by new `rancher-menu.spec.ts` - basically slightly adapted `menu.spec.ts` (without login of different users)~  menu.spec.ts has been adapted in the end
- epinio uninstalllation in rancher UI
* replaced the scenarios `with_default_options.spec.ts` (chrome) and `with_s3_and_external_registry.spec.ts` (firefox) by simple unit_test `menu.spec.ts`
* external registries are not tested anymore in Rancher UI tests
TODO:
- ~[ ] re-enable external registries - and …
=> Rancher UI tests without Epinio icon

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/master_std_ui.yml
UI tests seem to be ok after this bump:
- [Rancher-UI-2-Firefox Rancher-UI-2-Firefox #304](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3218931238/jobs/5264012402) -> OK
- [Rancher-UI-1-Chrome Rancher-UI-1-Chrome #281](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3219475022) -> OK
- [STD-UI-Latest-Firefox STD-UI-Latest-Firefox #133](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3218860701) -> OK
- [STD-UI-Latest-Chrome STD-UI-Latest-Chrome #209](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3219230238/jobs/5264344093) -> OK, with 1 single failure; seems corner case
=> bump cypress to k3s v1.24.6+k3s1

.github/workflows/build_latest_epinioUI.yml, .github/workflows/master_std_ui.yml
Fix for https://github.com/epinio/epinio-end-to-end-tests/issues/247
We freezing latest qa image from https://github.com/rancher/dashboard/tree/epinio-dev to  `epinio-standalone-v1.2.0.0.0.1` due to instability  on `epinio-dev`.
This will be reverted once stable
Checked on: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3274389955/jobs/5387848491
=> freezing dashboard image to v1.2.0.0.0.1

cypress/integration/unit_tests/menu.spec.ts, scripts/values-users.yaml
PR for https://github.com/epinio/epinio-end-to-end-tests/issues/248
Covers automated test of https://github.com/epinio/epinio/issues/1728
Adding loging username as number
=> adding login test username numeric

cypress/integration/unit_tests/menu.spec.ts
We are hit by network slowness when downloading binaries on runners, this should help a bit.
=> Check binaries by a loop

.github/workflows/build_latest_epinioUI.yml, .github/workflows/master_std_ui.yml
Bringing back latest `epinio-dev` after freezing it to `epinio-standalone-v1.2.0.0.0.1` [here](https://github.com/epinio/epinio-end-to-end-tests/issues/247#issuecomment-1282536556)
Basically excluded some env vars to prevent oom issues.
Tested on this CI ([Build Latest-STD-UI #1047](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3329677383/jobs/5507195439#step:5:11)) and working:
=> Bring back qa latest image to `epinio-dev` again

.github/workflows/build_latest_epinioUI.yml
Adding missing env var `RANCHER_ENV=epinio` after [this](https://github.com/epinio/epinio-end-to-end-tests/pull/261) fix  to the construction of latest epinio ui image
Tests:
Creation of [Build Latest-STD-UI #1050](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3330563308) passing::
UI test [STD-UI-Latest-Firefox #164](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3330656436/jobs/5509422750) passing
=> fixing missing env var RANCHER_ENV=epinio

.github/workflows/build_latest_epinioUI.yml
Related to https://github.com/epinio/epinio-end-to-end-tests/issues/263
Bump of Github actions.
Fixes annotation problems.
Proof:
Before: [Build Latest-STD-UI #1056](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3336099686)
After: [Build Latest-STD-UI #1057](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3336405942)
Checked this update does not affect the test here: [Rancher-UI-2-Firefox #336](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3336496926)
=> Updating actions for qa image

scripts/create_docker_secret.sh
This will enable using docker hub credentials for pulling images from k8s.
The original code was not complete, the credentials were created as `regcred` secret but not assigned to `default` serviceAccount.
=> Assign regcred secret to default sa

cypress/e2e/unit_tests/menu.spec.ts
Changing binary links from arm to amd 
Test local succesful:
=> Modifying binary link check to amd

.github/workflows/master_rancher_ui_workflow.yml
After changing CLI  binaries (arm64-> x86_64) by https://github.com/epinio/epinio-end-to-end-tests/pull/274 our Rancher-UI tests started to fail. I noticed that we don't do `epinio-ui` patching for rancher tests, this PR will address that.
Test run passed https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3582043482
=> Patch epinio-ui in rancher tests

cypress/e2e/unit_tests/menu.spec.ts
Fixes https://github.com/epinio/epinio-end-to-end-tests/issues/277
Implementation:
- Added a rule to skip downloading or checking links if length of characters in  version number in links page is >=7 characters (ie: `v1.5.1-25-ga9b168ab` and keep doing it if still less (ie: `v1.5.1`)
Results when version >= 7 characters:
Results when version <7 characters (binaries are downloaded):
=> Adapt binary link test to epinio server version

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_rancher_ui_workflow.yml
Updating dependency `cypress-io/github-action` to `v5`
Successful test here: [STD-UI-Latest-Firefox #284](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/3910607127/jobs/6682999823)
=> Updating  cypress-io/github-action to v5

.github/workflows/master_rancher_ui_experimental_workflow.yml
Adding Github action dispatch of to select `k3s` version for Master Rancher UI EXPERIMENTAL workflow
---
- k3s default version `v1.24.6+k3s1` passing: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4073973780
- k3s version  `v.1.25.5+k3s2` is correctly taken as parameter. The test fails correctly due to incompatibility of Rancher dasboard 2.7.1 with k8s >1.25)
=> [Cypress] Adding kubernetes version dispatch for Rancher Dashboard experimental

.github/workflows/actions_README.md
Adding `actions_README` to document experimental / customizeable flows to be used in CI in ad-hoc manner like https://github.com/epinio/epinio-end-to-end-tests/pull/285 or https://github.com/epinio/epinio-end-to-end-tests/pull/288
=> Adding actions Readme for ci experimental workflows

cypress/e2e/unit_tests/menu.spec.ts, cypress/support/epinio.ts
After update of new Dashboard page ([link](https://github.com/rancher/dashboard/pull/7519)), the amount of elements present in the lateral menu has changed.
This involves that a couple of position locators on these tests needed to be updated:
- Check Epinio menu
- Check binary links from version in menu
Tests passing: [STD UI experimental template #53](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4175951629/jobs/7231582940)
=> Adapting menu tests to new dashboard page

cypress/e2e/unit_tests/menu.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts
Implementation of https://github.com/epinio/epinio-end-to-end-tests/issues/238
- Implemented the following basic tests for DEX:
- **Check Dex login works with granted access**: It checks default user `admin@epinio.io` can login in Dex  and after granting access access to Epinio
- **Check Dex deny access**: Check that an allowed user will be able to connect to Dex but not to Epinio when access is not granted
- **Check users not allowed cannot connect to Dex**: verifies not allowed users cannot connect to Dex
- Since now default login page brings "Dex Login" as main button and some menu tests failed, I implemented as well a redirection to local user .
Test working locally
Working for both Rancher and STD UI tests:
[Rancher-UI-1-Chrome …
=> [Cypress-pr] - Basic Dex test implementation

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_rancher_ui_workflow.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml
This should fix all the rancher UI tests failures when setting regcreds-ghcr k8s secret for ghrc.io registry.
Also fixed other references to gh secrets in various workflows.
Test runs:
[STD UI experimental template](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4363252204)
[STD-UI-Latest-Firefox](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4363239091)
[STD-UI-Latest-Chrome](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4363237688) NOT RELATED FAILURE
[Rancher-UI-2-Firefox](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4363235556) NOT RELATED FAILURE
[Rancher-UI-1-Chrome](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4363234528) NOT RELATED FAILURE
=> Fix secret references

cypress/support/functions.ts
Issue:
This Config test `1) Create an application with a configuration, unbind the configuration and delete all` fail quite frequently waiting for app status 
```
1) Configuration testing
Create an application with a configuration, unbind the configuration and delete all:
AssertionError: Timed out retrying after 10000ms: expected '<tr.main-row>' to contain '1/1'
```
This happens because the implicit waiting is set is not correctly set in the specific function and takes only 10 seconds as default, when this process may take >15 seconds and even more at times..
This pr fixes that and extends if needed the time to 40s.
Tested in CI and working: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4447352410/jobs/7808794087#step:14:62
=> [Cyoress] Fix timeout misplacement and extending time

cypress/e2e/unit_tests/installation.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts
Implements test: https://github.com/epinio/epinio-end-to-end-tests/issues/301
- Added test for s3gw installation, check of Epinio route correctly deployed and uninstall.
- This tests is done prior the Epinio installation with `MinIO` since this latest one is the current default storage solution where the rest of tests will continue running after installation.
- Added cleansing mechanism for regular Epinio installation with `MinIO` if previous test did not uninstall correctly 
- Refactored test `Verify Epinio over ingress URL` by adding its content to a new function `checkEpinioInstallationRancher` for re-usabilty and clarity.
---
=> Cypress Adding s3gw test in Rancher.

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_std_ui_experimental.yml, Makefile, cypress/e2e/unit_tests/installation.spec.ts, cypress/e2e/unit_tests/menu.spec.ts, cypress/e2e/unit_tests/uninstall.spec.ts, cypress/support/functions.ts, scripts/install_rancher_experimental.sh
Adding more dispatches and other adaptations to our e2e tests
Added dispatches for :
- Epinio branch selection
- Helm version
- Node version
Added:
- Rancher version selector
- Created new script install_rancher_experimental to include PSP enable/disable flag. 
- Logic to enable/disable PSP flag according to the Kubernetes version
- Refactored logic to distinguish between the default Epinio chart (experimental) present in Rancher 2.7.2 and the one uploaded from the repo.
- Refactored where to get the ingresses from in the UI since `Network` was not always available without a refresh
- Refactored locators in menu test `Test buttons and links in dashboard page` to avoid occasional broken tests.
- Removed "falsy" `null` on uninstallation step that produced an incorrect selection of repo …
=> Cypress/Adding more dispatches to experimental wf and adapting Rancher tests to Rancher 2.7.2

cypress/support/functions.ts
Fixes: https://github.com/epinio/epinio-end-to-end-tests/issues/313
Adapts test `Download manifest from ui and push an app from it` to download manifest from `App export`
Local test passing:
Successful CI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4659370191/jobs/8246170544#step:14:148
=> Adapting manifest download to export app menu

cypress/e2e/unit_tests/menu.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts
Dex tests needed to be adapted after this issue: https://github.com/epinio/epinio/issues/2192
Basically, grant permission screen has been removed by Dex when source is correct.
- Removal of test `Check users not allowed cannot connect to Dex`
- Removal of associated useless functions
- Adapted check-in landing page after login within the `dexLogin` function. By default it checks the user is dex one. To disable use `{ checkLandingPage : false }` parameter within the function
- Local:
- CI: 
[Rancher-UI-1-Chrome #552](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4680018509/jobs/8291207604#step:3:135)
[STD UI experimental template #80 ](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4680372758/jobs/8291636573#step:14:159)
=> Cypress/ Adapt dex tests to no grant screen access

cypress/support/functions.ts
Given that now EPINIO_APP_DATA field has been hidden (https://github.com/epinio/ui/issues/220) test need to be adapted.
Summary of done:
- Changed locators for env vars fields during app creation
Currently env var count at the end remain as 1 until further work is done to completely remove it.
CI:
[STD-UI-Latest-Chrome #480](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4740888845/jobs/8417258156#step:14:60) . All green except test `Create mysql service, bind it to a Wordpress app and push it`. Retested [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4741592322/jobs/8418853005#step:14:69) and working
=> [Cypress] Adapting tests to EPINIO_APP_DATA env var field hidden

cypress/e2e/unit_tests/applications.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts, cypress/support/tests.ts
Implements: https://github.com/epinio/epinio-end-to-end-tests/issues/322
- Added test `Push Gitlab app and update sources` within applications to check `Gitlab` source type. It selects the source type, a user, a repo, a branch, and a commit and pushes the app
- Updates the deployed app to a different commit
- Updates the deployed app once again to a file source one
- Extended capabilities to commits and icons on `checkApp` function with `checkCommit` and `checkIcon`
- Refactored functions for reusability
- [STD UI experimental template #85](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4825639089)
- [STD-UI-Latest-Chrome #491](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4827838002/jobs/8601730431#step:14:148)
- Local:
=> [Cypress] Gitlab and source update test and refactoring

cypress/support/functions.ts
Adapting Dext tests to https://github.com/epinio/ui/issues/230
Implemented change on label check from `Log in with Dex` to `Log in with SSO`
CI successful [here](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4949186005/jobs/8850956292#step:14:78)
=> [Cyoress] changing dex label for sso in tests

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_std_ui_experimental.yml, cypress/e2e/unit_tests/installation.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts, scripts/install_epinio.sh
Implements: https://github.com/epinio/epinio-end-to-end-tests/issues/323 
- Added dispatch for Epinio version in STD UI experimental workflow
- Removed dispatch for grep title since 10 is maxed and this was unused.
- Selecting 'Include Prerelease Versions'' version in Rancher tests.
- [STD UI experimental template #125](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4977072308/jobs/8905743210#step:12:3672) (test against version 1.7.0)
- [Master Rancher UI EXPERIMENTAL workflow #99](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/4977180682/jobs/8906163445)
=> Add Version dispatch and allow RC in Rancher tests

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_std_ui_experimental.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml, .github/workflows/std_ui_latest_chrome.yml, .github/workflows/std_ui_latest_firefox.yml, cypress.config.ts, cypress/support/functions.ts, package-lock.json, package.json
Implements: https://github.com/epinio/epinio-end-to-end-tests/issues/333
- Bumped Cypress to 12.12.0
- Bumped rancher cypress to  `cypress/included:cypress-12.12.0-node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1`
- Some refactors needed according to the new version.
- Time waits refactors
- [STD-UI-Latest-Chrome #528](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5078326470/jobs/9123712992#step:14:46) (OK) 
- [Rancher-UI-1-Chrome #601](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5078031555/jobs/9122362265#step:3:66) (OK)
- [STD-UI-Latest-Firefox #429](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5109591161/jobs/9184544086#step:14:97) (OK)
- [Rancher-UI-2-Firefox …
=> Update e2e to cypress 12

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_std_ui_experimental.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml, .github/workflows/std_ui_latest_chrome.yml, .github/workflows/std_ui_latest_firefox.yml, cypress.config.ts, cypress/support/functions.ts, package-lock.json, package.json
Reverts epinio/epinio-end-to-end-tests#335
Although the update worked for the majority of workflows, it did not happened for the firefox_rancher one. 
After several tweaks with waits, adding envs for better performance as `CYPRESS_NO_COMMAND_LOG: 1`, it always happened to be unreliable for some tests with Firefox and Rancher.
Reverting
=> Revert "Update e2e to cypress 12"

cypress/support/tests.ts
Updating manifest.json to manifest.yaml after merge of https://github.com/rancher/dashboard/pull/8970 (as part of https://github.com/epinio/ui/issues/227) to prevent test failure
Local:
```
====================================================================================================
(Run Starting)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Cypress:        10.11.0                                                                        │
│ Browser:        Electron 106 (headless)                                                        │
│ Node Version:   v18.0.0 (/home/mmartin/.nvm/versions/node/v18.0.0/bin/node)                    │
│ Specs:          1 found (applications.spec.ts) …
```
=> Changing manifest.json for manifest.yaml

cypress/support/functions.ts
[Rancher-UI-1-Chrome #613](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5166908233/jobs/9307459896) started to failed during installation a couple of days ago. 
The problem seems to be a new overlay screen with 'Loading' taking a bit to go away both during installation and unistall.
Adding implicit wait for the element 'Loading' not to be present (max 20 secs)
Local
CI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5176482912/jobs/9330408393
=> [Cypress] Fixing Rancher Install Test Chrome (overlay screen 'loading')

cypress/e2e/unit_tests/menu.spec.ts
- Implemented home button link check (implementation  https://github.com/epinio/epinio-end-to-end-tests/issues/254), reloading page, and observing text change.
- Adding slicing version logic
- Splitting about page test from binaries downloads
- Adapted locators to new UI
- Refactoring
Local tests: 
CI: [STD UI experimental template #146](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5208757596/jobs/9397721036#step:14:64)
Note: left test `Check binaries, version related links and downloads from About menu` still uncommented until the next version is effectively released and binaries can be found
=> [Cypress] Adding homebutton check, About test split and refactors

Makefile, scripts/create_docker_secret.sh
This is about switching the serviceAccount approach for setting up registry credentials what is namespace scoped.
This new approch will set k3s registries globally so it will be not NS scoped anymore.
the values can be verified on node:
```
cat /var/lib/rancher/k3s/agent/etc/containerd/config.toml
```
=> Global registry credentials for k3s

cypress/e2e/unit_tests/menu.spec.ts
PR for https://github.com/epinio/epinio-end-to-end-tests/issues/347
The issue seemed to be related with the attempt to reload a page after executing a `cy.visit` that did not seem to finish. Changing the behavior of the visit to actually following the link and explicitly waiting for the page to load before reloading seems a  logical solution
Changed cv.visit for clicking on the link and implicit wait of elements
Successfully passed 3 times:
- https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5355961505
- https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5356224586
- https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5356487433
=> Change `cy.visit` in about page for link click + implicit wait for loading

.github/workflows/update-tests-description.yaml
I made a mistake with my `sed` command...
=> ci: fix token in update-tests-description workflow

cypress/e2e/unit_tests/applications.spec.ts, cypress/support/e2e.ts, cypress/support/functions.ts, cypress/support/tests.ts
Implemented: https://github.com/epinio/epinio-end-to-end-tests/issues/359
- Adapted already existing test to use commit redeploy logic in 1 case instead of 2 source updates
- Added test coverage for commit redeployment functionality
- Renamed test title
[STD UI experimental template #164](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/5584701631/jobs/10206452544)
=> Added new commit redeploy logic 

.github/workflows/master_rancher_ui_workflow.yml, .github/workflows/scenario_1_chrome_rancher_ui.yml, .gitignore, cypress.config.ts, cypress/e2e/unit_tests/installation.spec.ts, cypress/plugins/index.ts, cypress/support/e2e.ts, cypress/support/functions.ts
ref: https://github.com/epinio/epinio-end-to-end-tests/issues/361
* `installEpinio` function modifed, now it accepts optional `s3Storage: Cypress.env('s3Storage')` string values `s3gw`, `s3`, and "" aka `none` , booleans args for setting `s3` and `s3gw` were removed
* fixed also selector for aws `s3` in the same function but it is not used anywhere (but works, can be used in https://github.com/epinio/epinio-end-to-end-tests/issues/236)
* existing workflow for `Rancher-UI-1-Chrome` extended for triggering another job related to s3gw where only `applications.spec.ts` with tag `@appl-1` (simplest app depoloyment test) is used
* the workflow is using different runner classes for the jobs so it should not slow down the execution time (jobs are running in parallel)
Testrun: …
=> Deploy app on s3gw

cypress/support/functions.ts
Adapting namespace [failed test](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6080085442/job/16495441908#step:14:62) from `Create a New Namespace` to new string without capitalization `Create a new Namespace`: 
CI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6081336751
=> Adapting string to small cap in "namespace"

Makefile, scripts/install_cert-manager.sh, scripts/install_epinio.sh, scripts/patch_epinio-ui.sh
Mainly cleanup but the changes will save ~40s for E deploment
* sleep after patching `epinio-server` pod replaced by waiting for resource
* sleep between `login` and `info` removed
* removed duplicated `install-cert-manager` target
* added wait for `epinio-ui` pod resource after ui patching to `latest-next`
Tested locally by `make install-k3s install-cert-manager install-epinio patch-epinio-ui`
=> Makefile cleanup

scripts/patch_epinio-ui.sh
Once you delete the epinio-ui pod it will repull the image.
* doesn't have an impact on CI. This will just set `imagePullPolicy` to `Always` in UI deployment to prevent using outdated image within `make patch-epinio-ui` - if the image has been changed already you will have to delete the ui pod manually anyway.
* updated link to release-next workflow
=> Always (re)pull epinio-ui:latest-next

scripts/patch_epinio-ui.sh
I had to duplicate the `wait` to make it work again.
Testrun: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6097296605
spec: `menu`
grep tags: `@menu-1` (well I entered wrong value `@menu1` but doesn't matter, the affected part is executed earlier than cy)
=> Fix wait after patching imagePullPolicy

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/scenario_2_firefox_rancher_ui.yml
Changing default runner `ui-e2e-2` (faulty at times) to `ui-e2e-3`
CI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6160083136/job/16716218177
=> Switching default runner for rancher tests

cypress/e2e/unit_tests/menu.spec.ts
Helps / fixes: https://github.com/epinio/epinio-end-to-end-tests/issues/378
Added `cy.then` before a reload to ensure this one ends completely.
This seems to have eased the flakiness on subsequent tests both for Rancher and STD_UI: 
- [Rancher-UI-2-Firefox #745](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6171514597/job/16750279071#step:3:74)
- [STD-UI-Latest-Chrome #664 ](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6171828120/job/16750847610#step:14:60)
=> Implementing cy.then before reload on menu tests

cypress/e2e/unit_tests/menu.spec.ts
Temporarily disabling reloading on specific test `Check "About" page and main links` to avoid page crashing and at times subsequent malfunctioning on other tests
Example
CI: 
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6219596390/job/16877965897
=> Disabling reload to avoid page crashing

.github/workflows/scenario_1_chrome_rancher_ui.yml, .github/workflows/std_ui_latest_firefox.yml
Spacing cron times on 2 workflows to better ensure no API calls overlap between workflows.
After change timing will be as follows:
- `scenario_2_firefox_rancher_ui.yml`: 2:00
- `scenario_1_chrome_rancher_ui.yml`: 2:30 (updated, used to be 2:00)
- `std_ui_latest_firefox.yaml`: 3:00 (updated, used to be 2:00)
- `std_ui_latest_chrome.yaml`: 4:00
=> spacing cron jobs

scripts/install_epinio.sh
This should make STD-UI tests work just by replacing unavailable epinio-unpacker:v1.10.0-rc1 (deleted by cleanup job) with latest one.
RANCHER-UI will keep failing
=> WORKAROUND: epinio-staging-scripts using epinio-unpacker:latest

scripts/install_epinio.sh
This PR is trying to prevent following message when doing `epinio login` just after E deployment.
```
❌  error verifying credentials: error while connecting to the Epinio server: empty
```
Testrun: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6271463380
=> Let Epinio settle after deployment

.github/workflows/scenario_1_chrome_rancher_ui.yml
Changing labels from `ui-e2e-0` to `ui-e2e-1` in order to succeed job `cypress-epinio-installation`, step `Initialize containers` on `rancher-chrome` test, as the current runner `gha08-runner-0`  is unhealthy as described in https://github.com/epinio/epinio/issues/2598
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6273905943
Note the difference before after changing runner:
=> Changing runner to avoid container init problem on previous one

cypress/fixtures/read_from_worpress_file.txt, cypress/support/functions.ts
Updating Wordpress version from 8.0.x to 8.1.x to avoid failures as:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6688205013/job/18169920587#step:14:162
Unblocked after https://github.com/epinio/epinio/issues/2686
---
CI: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6730558658/job/18294100107#step:14:67
=> Updating wordpress version for UI tests

.github/workflows/master_rancher_ui_experimental_workflow.yml, .github/workflows/master_rancher_ui_workflow.yml, cypress/support/functions.ts
Removing need of typing CORS after removal of specified CORS box [here](https://github.com/epinio/helm-charts/pull/504#issuecomment-1810465891) in Rancher UI
Successful test here:
https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6892172299/job/18750492603
=> Cypress / removing manual entering of CORS

cypress/e2e/unit_tests/menu.spec.ts
Setting download `downloadBinaries` and  `checkSeeAllPackagePage` to false while `-rc`tag version is out to prevent incorrect failure on test `Check binaries, version related links and downloads from About menu` as [this](https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6899066604/job/18770322994#step:3:90) one:
https://github.com/epinio/epinio-end-to-end-tests/blob/88ff5174ca52c54e446cbf76886ff03d80d0529d/cypress/e2e/unit_tests/menu.spec.ts#L70-L71
CI passing: https://github.com/epinio/epinio-end-to-end-tests/actions/runs/6900520593/job/18773805080#step:14:64
=> Cypress/disabling binary downloads until -rc tag is not present
